
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest  

    steps:
    - name: Checkout    
      
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = "AAAA"
