name: .NET Core Desktop4

on:
  push:

jobs:

  build:

    runs-on: windows-latest  
    

    steps:
    #- name: Checkout    
     # #uses: actions/checkout@v3
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = "AAAA"
