name: Hello
on: [push]
jobs:
  First-Job:
    name: " First Job"
    runs-on: ubuntu-latest
    steps:
     - name: 'Step One'
       run: |
         echo "Hello Wordl-1!"
         echo "Hello Wordl-2!"
         echo "Hello Wordl-3!"
   
