name: Hello
on: [push]
jobs:
  First-Job:
    name: " First Job"
    runs-on: [self-hosted]
    steps:
     - name: 'Step One'
       run: |
           echo "Hello Wordl-1!"
           $envName = "abc"
           echo "ABC = $envName"
           echo "Hello Wordl-3!"
   
