name: Hello
on: [push]
jobs:
  First-Job:
    name: "AAAA"
    runs-on: ubuntu-latest
    steps:
      - run:
         echo "Hello Wordl!"

         $var1 = "aaaa" 
         echo $var1

         $var2 = "bbbb" 
         echo $var2
         
         

